local Color, colors, Group, groups, styles = require("colorbuddy").setup()

Color.new("sakura_",           "#FEDFE1")
Color.new("momo",              "#F596AA")
Color.new("benihi",            "#F75C2F")
Color.new("sahregaki",         "#FFBA84")
Color.new("hiwa",              "#BEC23F")
Color.new("veludo",            "#096148")
Color.new("aomidori",          "#00AA90")
Color.new("mizu",              "#81C7D4")
Color.new("ouchi",             "#9B90C2")
Color.new("tsutsuji",          "#E03C8A")
Color.new("shironeri",         "#FCFAF2")
Color.new("sumi",              "#1C1C1C")
Color.new("kuro",              "#080808")
Color.new("kurenai",           "#CB1B45")
Color.new("benifuji",          "#B481BB")
Color.new("usu",               "#B28FCE")
Color.new("yamabuki",          "#FFB11B")
Color.new("seiji",             "#69B0AC")
Color.new("rikyunezumi",       "#707C7D")
Color.new("toki",              "#EEA9A9")
Color.new("sangosyu",          "#F17C67")
Color.new("akashirotsurubami", "#E1A679")
Color.new("tamago",            "#F9BF45")

Color.new('white',             "#FCFAF2")
Color.new('red',               '#CB1B45')
Color.new('green',             '#BEC23F')
Color.new('yellow',            '#FFB11B')
Color.new('blue',              '#81C7D4')
Color.new('aqua',              '#00AA90')
Color.new('cyan',              '#8FBCBB')
Color.new('purple',            '#B28FCE')
Color.new('violet',            '#B28FCE')
Color.new('orange',            '#FFBA84')




Group.new('Normal',         colors.none,         colors.none)
Group.new('Function',       colors.mizu,       colors.none,    styles.NONE)
Group.new('ErrorMsg',          colors.shironeri,      colors.kurenai,    styles.bold)
Group.new('ErrorMsg',       colors.shironeri,       colors.kurenai, styles.bold)
Group.new('WarningMsg',     colors.shironeri,       colors.yamabuki, styles.bold)
Group.new('Boolean',        colors.usu,       colors.none,    styles.NONE)
Group.new('Character',      colors.yamabuki,      colors.none,    styles.NONE)
Group.new('Comment',        colors.rikyunezumi, colors.none,    styles.italic)
Group.new("Conditional",    colors.aomidori,       colors.none,    styles.italic)
-- Group.new("Constant",       colors.nord_4,       colors.none,    styles.italic)
Group.new("Define",         colors.sangosyu,       colors.none,    styles.NONE)
-- Group.new("Delimiter",      colors.nord_6,       colors.none,    styles.NONE)
-- Group.new("Exception",      colors.nord_9,       colors.none,    styles.NONE)
-- Group.new("Float",          colors.nord_15,      colors.none,    styles.NONE)
-- Group.new("Identifier",     colors.nord_4,       colors.none,    styles.NONE)
Group.new("Include",        colors.tamago,       colors.none,    styles.NONE)
Group.new("Keyword",        colors.toki,       colors.none,    styles.italic)
Group.new("Label",          colors.sakura_,       colors.none,    styles.NONE)
Group.new("Number",         colors.mizu,      colors.none,    styles.NONE)
Group.new("Operator",       colors.usu,       colors.none,    styles.NONE)
-- Group.new("PreProc",        colors.nord_9,       colors.none,    styles.NONE)
-- Group.new("Repeat",         colors.nord_9,       colors.none,    styles.NONE)
-- Group.new("Special",        colors.nord_4,       colors.none,    styles.NONE)
-- Group.new("SpecialChar",    colors.nord_13,      colors.none,    styles.NONE)
-- Group.new("SpecialComment", colors.nord_8,       colors.none,    styles.italic)
-- Group.new("Statement",      colors.nord_9,       colors.none,    styles.NONE)
-- Group.new("StorageClass",   colors.nord_9,       colors.none,    styles.NONE)
Group.new("String",         colors.yamabuki,      colors.none,    styles.NONE)
-- Group.new("Structure",      colors.nord_9,       colors.none,    styles.NONE)
-- Group.new("Tag",            colors.nord_4,       colors.none,    styles.NONE)
-- Group.new("Title",          colors.nord_4,       colors.none)
Group.new("Todo",           colors.kuro,      colors.akashirotsurubami,    styles.NONE)
-- Group.new("Type",           colors.nord_9,       colors.none,    styles.NONE)
-- Group.new("Typedef",        colors.nord_9,       colors.none,    styles.NONE)
-- Group.new("CursorColumn",   colors.nord_1,       colors.none,    styles.NONE)
-- Group.new("LineNr",         colors.nord_9,       colors.none,    styles.NONE)
-- Group.new("CursorLineNr",   colors.nord_5,       colors.none,    styles.NONE)
-- Group.new("Line",           colors.nord_12,      colors.none,    styles.bold)
-- Group.new("SignColumn",     colors.none,         colors.none,    styles.NONE)
-- Group.new("StatusLine",     colors.nord_8,       colors.nord_3,    styles.NONE)
--


Group.new("ColorColumn",  colors.kuro,     colors.sakura_)
Group.new("CursorLine",   colors.none,     colors.sumi)
Group.new("Cursor",       colors.kuro,     colors.sakura_)
Group.new("iCursor",      colors.sumi,     colors.sakura_)
Group.new("Visual",       colors.kuro,     colors.sakura_)
Group.new("VisualNOS",    colors.kuro,     colors.sakura_)
Group.new("LineNr",       colors.sakura_,  colors.none)
Group.new("CursorLineNr", colors.sangosyu, colors.none)
